<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CrearTipoSolicitudTable extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $rows = [
            ['id_tiposolicitud'=>1,  'desc_tiposolicitud'=>'Solicitud de Servicio',                                 'idarea'=>3,  'estado'=>1],
            ['id_tiposolicitud'=>2,  'desc_tiposolicitud'=>'Solicitud de Compra de Activo',                         'idarea'=>3,  'estado'=>1],
            ['id_tiposolicitud'=>3,  'desc_tiposolicitud'=>'Solicitudes',                                           'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>4,  'desc_tiposolicitud'=>'Incidentes',                                            'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>5,  'desc_tiposolicitud'=>'Desarrollo Nivel 1',                                    'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>6,  'desc_tiposolicitud'=>'Desarrollo nivel 2',                                    'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>7,  'desc_tiposolicitud'=>'Soporte Nivel 1',                                       'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>8,  'desc_tiposolicitud'=>'Soporte Nivel 2',                                       'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>9,  'desc_tiposolicitud'=>'Proyecto',                                              'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>10, 'desc_tiposolicitud'=>'Biomedica',                                             'idarea'=>2,  'estado'=>1],
            ['id_tiposolicitud'=>11, 'desc_tiposolicitud'=>'Sistemas',                                              'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>12, 'desc_tiposolicitud'=>'Activos',                                               'idarea'=>14, 'estado'=>1],
            ['id_tiposolicitud'=>13, 'desc_tiposolicitud'=>'Servicios',                                             'idarea'=>15, 'estado'=>1],
            ['id_tiposolicitud'=>14, 'desc_tiposolicitud'=>'Otras Compras',                                         'idarea'=>16, 'estado'=>1],
            ['id_tiposolicitud'=>15, 'desc_tiposolicitud'=>'Necesidades de dotacion, carnet, yoyos, tiras ...',     'idarea'=>4,  'estado'=>1],
            ['id_tiposolicitud'=>16, 'desc_tiposolicitud'=>'PQR del personal para TH',                              'idarea'=>4,  'estado'=>1],
            ['id_tiposolicitud'=>17, 'desc_tiposolicitud'=>'Copias de documentos de las hojas de vida',             'idarea'=>4,  'estado'=>1],
            ['id_tiposolicitud'=>18, 'desc_tiposolicitud'=>'Solicitudes de plataforma colegio de gestion del riesgo','idarea'=>4,  'estado'=>1],
            ['id_tiposolicitud'=>19, 'desc_tiposolicitud'=>'Novedades huellero',                                    'idarea'=>4,  'estado'=>1],
            ['id_tiposolicitud'=>20, 'desc_tiposolicitud'=>'Traslado de personal',                                  'idarea'=>4,  'estado'=>1],
            ['id_tiposolicitud'=>21, 'desc_tiposolicitud'=>'Pedidos de papeleria, bombas',                          'idarea'=>4,  'estado'=>1],
            ['id_tiposolicitud'=>22, 'desc_tiposolicitud'=>'Solicitudes de capacitaciones',                         'idarea'=>4,  'estado'=>1],
            ['id_tiposolicitud'=>23, 'desc_tiposolicitud'=>'Eliminar / Modificar Estudios en PACS',                 'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>24, 'desc_tiposolicitud'=>'Crear / Modificar Usuario PSL',                         'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>25, 'desc_tiposolicitud'=>'Crear usuario RIS / Correo electrónico',                 'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>26, 'desc_tiposolicitud'=>'Credenciales de acceso Nómina Web',                     'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>27, 'desc_tiposolicitud'=>'Cambio Division / Caja PSL',                            'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>28, 'desc_tiposolicitud'=>'Mover estudios PACS - Previos',                         'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>29, 'desc_tiposolicitud'=>'Agregar / Revocar Privilegios en EPSILON',              'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>30, 'desc_tiposolicitud'=>'Restaurar estudio en PACS',                             'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>31, 'desc_tiposolicitud'=>'Desbloquear Estudio',                                   'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>32, 'desc_tiposolicitud'=>'Separar estudios combinados a pacientes',               'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>33, 'desc_tiposolicitud'=>'Asignar / Revocar Permisos RIS',                        'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>34, 'desc_tiposolicitud'=>'Modificar fecha de estudios en RIS',                    'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>35, 'desc_tiposolicitud'=>'Desbloquear estudio en RIS',                            'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>36, 'desc_tiposolicitud'=>'Instalación PSL',                                       'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>37, 'desc_tiposolicitud'=>'Acceso remoto a SIPE',                                  'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>38, 'desc_tiposolicitud'=>'Inactivar Usuario SIPE',                                'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>39, 'desc_tiposolicitud'=>'Crear usuario en SIPE',                                 'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>40, 'desc_tiposolicitud'=>'Error PSL',                                             'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>41, 'desc_tiposolicitud'=>'Problemas Con Agentbox',                                'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>42, 'desc_tiposolicitud'=>'Modificar horario cuadro de turnos',                    'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>43, 'desc_tiposolicitud'=>'Modificar documento paciente en RIS',                   'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>44, 'desc_tiposolicitud'=>'Modificar especialista estudios aprobados en RIS',      'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>45, 'desc_tiposolicitud'=>'Crear convencion cuadro de turnos',                     'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>46, 'desc_tiposolicitud'=>'Devolucion Estudio Aquila',                             'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>47, 'desc_tiposolicitud'=>'Trazabilidad estudio RIS',                              'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>48, 'desc_tiposolicitud'=>'Modificar informacion especialistas',                   'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>49, 'desc_tiposolicitud'=>'Modificar fecha cita RIS',                              'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>50, 'desc_tiposolicitud'=>'Estudio no parecen en AQUILA',                          'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>51, 'desc_tiposolicitud'=>'Reportes Aquila',                                       'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>52, 'desc_tiposolicitud'=>'Soporte Aquila',                                        'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>53, 'desc_tiposolicitud'=>'Envio resultados Correo RIS',                           'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>54, 'desc_tiposolicitud'=>'Crear usuario en AQUILA',                               'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>55, 'desc_tiposolicitud'=>'Portal Resultados AQUILA',                              'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>56, 'desc_tiposolicitud'=>'Estudios no pasan al PACS',                             'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>57, 'desc_tiposolicitud'=>'Recuperar informe estudio en RIS',                      'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>58, 'desc_tiposolicitud'=>'Crear ERP en RIS',                                      'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>59, 'desc_tiposolicitud'=>'Error en RIS',                                          'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>60, 'desc_tiposolicitud'=>'Problemas con el Robot',                                'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>61, 'desc_tiposolicitud'=>'Modificar Reporte Epsilon',                             'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>62, 'desc_tiposolicitud'=>'Devolcion estudio RIS',                                 'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>63, 'desc_tiposolicitud'=>'Modificar tipo contraste RIS',                          'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>64, 'desc_tiposolicitud'=>'Modificar reporte RIS',                                 'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>65, 'desc_tiposolicitud'=>'Modificar Plantilla resultados',                        'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>66, 'desc_tiposolicitud'=>'Eliminar nota aclaratoria RIS',                         'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>67, 'desc_tiposolicitud'=>'Modificar Avales',                                      'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>68, 'desc_tiposolicitud'=>'Creacion Tipo Ausentismo en cuadro de turnos',          'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>69, 'desc_tiposolicitud'=>'Eliminar archivo adjunto solicitud',                    'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>70, 'desc_tiposolicitud'=>'Crear Reporte Aquila',                                  'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>71, 'desc_tiposolicitud'=>'Asignar / Revocar privilegios AQUILA',                  'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>72, 'desc_tiposolicitud'=>'Creación de EPS',                                       'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>73, 'desc_tiposolicitud'=>'Verificar estudio',                                     'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>74, 'desc_tiposolicitud'=>'Eliminar turno',                                        'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>75, 'desc_tiposolicitud'=>'Activar usuario Epsilon',                               'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>76, 'desc_tiposolicitud'=>'Error RIS Angiodinamia',                                'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>77, 'desc_tiposolicitud'=>'Modificar ERP en estudio ya realizado en RIS',          'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>78, 'desc_tiposolicitud'=>'Asignar / Revocar Permisos RIS Angiodinamia',           'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>79, 'desc_tiposolicitud'=>'Crear / Modificar Usuario RIS Angiodinamia',            'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>80, 'desc_tiposolicitud'=>'Actualizar Página Web',                                 'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>81, 'desc_tiposolicitud'=>'Recuperar Turnos Eliminados',                           'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>82, 'desc_tiposolicitud'=>'Modificar Contraseña RIS',                              'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>83, 'desc_tiposolicitud'=>'Crear Usuario Metabase',                                'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>84, 'desc_tiposolicitud'=>'Modificar Cita RIS',                                    'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>85, 'desc_tiposolicitud'=>'Portal Resultados RIS',                                 'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>86, 'desc_tiposolicitud'=>'Estudio Bloqueado RIS',                                 'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>87, 'desc_tiposolicitud'=>'Soporte Página Web',                                    'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>88, 'desc_tiposolicitud'=>'Devolución Estudio RIS',                                'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>89, 'desc_tiposolicitud'=>'Habilitar Usuario AQUILA',                              'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>90, 'desc_tiposolicitud'=>'Restaurar Estudio Cancelado RIS',                       'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>91, 'desc_tiposolicitud'=>'Crear usuario PSL / AQUILA',                            'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>92, 'desc_tiposolicitud'=>'Eliminar estudo agendamiento RIS',                      'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>93, 'desc_tiposolicitud'=>'Crear Reporte RIS',                                     'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>94, 'desc_tiposolicitud'=>'Sanitarios',                                            'idarea'=>8,  'estado'=>1],
            ['id_tiposolicitud'=>95, 'desc_tiposolicitud'=>'Lavamanos',                                             'idarea'=>8,  'estado'=>1],
            ['id_tiposolicitud'=>96, 'desc_tiposolicitud'=>'Pinturas',                                              'idarea'=>8,  'estado'=>1],
            ['id_tiposolicitud'=>97, 'desc_tiposolicitud'=>'Chapas',                                                'idarea'=>8,  'estado'=>1],
            ['id_tiposolicitud'=>98, 'desc_tiposolicitud'=>'Escritorios',                                           'idarea'=>8,  'estado'=>1],
            ['id_tiposolicitud'=>99, 'desc_tiposolicitud'=>'Iluminación',                                           'idarea'=>8,  'estado'=>1],
            ['id_tiposolicitud'=>100,'desc_tiposolicitud'=>'Puntos de red',                                         'idarea'=>8,  'estado'=>1],
            ['id_tiposolicitud'=>101,'desc_tiposolicitud'=>'Conexiones Elétricas',                                  'idarea'=>8,  'estado'=>1],
            ['id_tiposolicitud'=>102,'desc_tiposolicitud'=>'Pisos',                                                 'idarea'=>8,  'estado'=>1],
            ['id_tiposolicitud'=>103,'desc_tiposolicitud'=>'Puertas',                                               'idarea'=>8,  'estado'=>1],
            ['id_tiposolicitud'=>104,'desc_tiposolicitud'=>'Ventanas',                                              'idarea'=>8,  'estado'=>1],
            ['id_tiposolicitud'=>105,'desc_tiposolicitud'=>'Mobiliarios',                                           'idarea'=>8,  'estado'=>1],
            ['id_tiposolicitud'=>106,'desc_tiposolicitud'=>'Cámaras CCTV',                                          'idarea'=>8,  'estado'=>1],
            ['id_tiposolicitud'=>107,'desc_tiposolicitud'=>'Acampañamientos',                                       'idarea'=>8,  'estado'=>1],
            ['id_tiposolicitud'=>108,'desc_tiposolicitud'=>'Mobiliario Clínico',                                    'idarea'=>8,  'estado'=>1],
            ['id_tiposolicitud'=>109,'desc_tiposolicitud'=>'Red de gases medicinales',                              'idarea'=>8,  'estado'=>1],
            ['id_tiposolicitud'=>110,'desc_tiposolicitud'=>'Cafeteras',                                             'idarea'=>8,  'estado'=>1],
            ['id_tiposolicitud'=>111,'desc_tiposolicitud'=>'Pocetas',                                               'idarea'=>8,  'estado'=>1],
            ['id_tiposolicitud'=>112,'desc_tiposolicitud'=>'Otros',                                                 'idarea'=>8,  'estado'=>1],
            ['id_tiposolicitud'=>113,'desc_tiposolicitud'=>'Sillas',                                                'idarea'=>8,  'estado'=>1],
            ['id_tiposolicitud'=>114,'desc_tiposolicitud'=>'Modificar fechas Nota Credito en PSL',                  'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>115,'desc_tiposolicitud'=>'Crear usuario RIS / PSL / AQUILA',                      'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>116,'desc_tiposolicitud'=>'Crear Médico RIS / AQUILA',                              'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>117,'desc_tiposolicitud'=>'Crear Médico RIS / AQUILA',                              'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>118,'desc_tiposolicitud'=>'Problemas Integarción Atrys',                           'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>119,'desc_tiposolicitud'=>'Apertura Cuadro turnos',                                'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>120,'desc_tiposolicitud'=>'Inactivar Médico - RIS',                                'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>121,'desc_tiposolicitud'=>'Cambiar estados Preagendamiento',                       'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>122,'desc_tiposolicitud'=>'Pieza Gráfica',                                         'idarea'=>9,  'estado'=>1],
            ['id_tiposolicitud'=>123,'desc_tiposolicitud'=>'Fotografía',                                            'idarea'=>9,  'estado'=>1],
            ['id_tiposolicitud'=>124,'desc_tiposolicitud'=>'Apoyo en campañas',                                     'idarea'=>9,  'estado'=>1],
            ['id_tiposolicitud'=>125,'desc_tiposolicitud'=>'Video',                                                 'idarea'=>9,  'estado'=>1],
            ['id_tiposolicitud'=>126,'desc_tiposolicitud'=>'Todas las anteriores',                                   'idarea'=>9,  'estado'=>1],
            ['id_tiposolicitud'=>127,'desc_tiposolicitud'=>'Crear ERP en RIS Angiodinamia',                          'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>128,'desc_tiposolicitud'=>'Error en Solicitudes de compras',                        'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>129,'desc_tiposolicitud'=>'No carga lista de trabajo AQUILA',                       'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>130,'desc_tiposolicitud'=>'RIS Concordancia',                                       'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>131,'desc_tiposolicitud'=>'Modificar Nombre Servicio en RIS',                       'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>132,'desc_tiposolicitud'=>'Problemas Integración SUNUBE',                           'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>133,'desc_tiposolicitud'=>'Actualizar listado de equipos biomédicos',               'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>134,'desc_tiposolicitud'=>'Requerimiento Desarrollo SUNUBE',                        'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>135,'desc_tiposolicitud'=>'Corregir Facturas PSL',                                  'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>136,'desc_tiposolicitud'=>'Error BTW',                                              'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>137,'desc_tiposolicitud'=>'Inactivar Médico',                                       'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>138,'desc_tiposolicitud'=>'Paso Imágenes al PACS',                                  'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>139,'desc_tiposolicitud'=>'Señalización',                                           'idarea'=>9,  'estado'=>1],
            ['id_tiposolicitud'=>140,'desc_tiposolicitud'=>'Otro (especifique)',                                     'idarea'=>9,  'estado'=>1],
            ['id_tiposolicitud'=>141,'desc_tiposolicitud'=>'Imágenes combinadas con las de otro paciente',           'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>142,'desc_tiposolicitud'=>'Modificar número de acceso',                             'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>143,'desc_tiposolicitud'=>'Habilitar Registro Disponibilidades',                    'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>144,'desc_tiposolicitud'=>'Estudio Perdido',                                        'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>145,'desc_tiposolicitud'=>'Crear usuario plataforma Bizneo',                         'idarea'=>4,  'estado'=>1],
            ['id_tiposolicitud'=>146,'desc_tiposolicitud'=>'Inactivar usuario en AQUILA / RIS',                       'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>147,'desc_tiposolicitud'=>'Soporte Atrys',                                           'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>148,'desc_tiposolicitud'=>'Crear Reporte Metabase',                                  'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>149,'desc_tiposolicitud'=>'Soporte Nómina Web',                                     'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>150,'desc_tiposolicitud'=>'Modificar fecha Facturas SPL',                            'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>151,'desc_tiposolicitud'=>'Asignar / revocar privilegios AQUILA',                    'idarea'=>1,  'estado'=>2],
            ['id_tiposolicitud'=>152,'desc_tiposolicitud'=>'Incidente',                                              'idarea'=>1,  'estado'=>1],
            ['id_tiposolicitud'=>153,'desc_tiposolicitud'=>'Requerimiento',                                          'idarea'=>1,  'estado'=>1],
        ];

        // Safe re-run: update if the id already exists
        DB::table('tipo_solicitud')->upsert(
            $rows,
            ['id_tiposolicitud'],                 // conflict key
            ['desc_tiposolicitud','idarea','estado'] // columns to update
        );
    }
}
